import type { OfflineSnapshot } from "@/hooks/useOfflineData";
import { Activity, Award, ClipboardList, CloudOff, UserCheck, UserRoundX } from "lucide-react";

const cards = [
  { key: "activePlayers", label: "لاعبون نشطون", icon: UserCheck, tone: "green" }, { key: "testRecords", label: "نتائج الاختبارات", icon: ClipboardList, tone: "gold" },
  { key: "averageTeamAchievement", label: "متوسط إنجاز الفريق", icon: Award, tone: "blue", suffix: "%" }, { key: "excellentPercentage", label: "نسبة الممتاز", icon: Activity, tone: "green", suffix: "%" },
  { key: "absentToday", label: "غياب اليوم", icon: UserRoundX, tone: "red" }, { key: "pendingSync", label: "عمليات معلّقة", icon: CloudOff, tone: "gray" },
] as const;

export function OverviewPanel({ data }: { data: OfflineSnapshot }) {
  return <section className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-[#ad8130]">نظرة تشغيلية</p><h2 className="mt-1 text-2xl font-black tracking-tight">لوحة المتابعة</h2><p className="mt-1 text-sm text-[#718078]">قراءة حية من قاعدة البيانات المحلية، بلا بيانات تجريبية.</p></div><div className="rounded-xl border border-[#d6e1d8] bg-white px-3 py-2 text-xs text-[#5b6e63]">{data.metrics.documentedStandards} معيار مرجعي موثّق</div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map((card) => { const Icon = card.icon; const value = data.metrics[card.key]; return <article key={card.key} className="rounded-2xl border border-[#dce5de] bg-white p-4 shadow-[0_8px_24px_rgba(20,37,31,.04)]"><div className="flex items-start justify-between"><div className={`grid h-9 w-9 place-items-center rounded-xl ${card.tone === "gold" ? "bg-[#fbf1d9] text-[#ad8130]" : card.tone === "red" ? "bg-[#faece9] text-[#b34d3e]" : card.tone === "blue" ? "bg-[#e8f2f1] text-[#24716b]" : card.tone === "gray" ? "bg-[#eef0ed] text-[#65726b]" : "bg-[#e8f3ea] text-[#28714d]"}`}><Icon className="h-4 w-4" /></div><span className="text-xs text-[#75827b]">محلي</span></div><div className="mt-6 text-3xl font-black tracking-tight">{value}{"suffix" in card ? card.suffix : ""}</div><p className="mt-1 text-sm font-semibold text-[#5c6e65]">{card.label}</p></article>; })}</div>
    <div className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]">
      <article className="rounded-2xl border border-[#dce5de] bg-white p-5"><h3 className="font-extrabold">آخر نتائج مسجلة</h3><div className="mt-4 space-y-3">{data.latestResults.length ? data.latestResults.map((result) => { const player = data.players.find((item) => item.id === result.playerId); const test = data.tests.find((item) => item.id === result.testId); return <div key={result.id} className="flex items-center justify-between border-b border-[#eef2ee] pb-3 last:border-none last:pb-0"><div><p className="font-bold">{player?.name ?? "لاعب محذوف"}</p><p className="text-xs text-[#75827b]">{test?.nameAr ?? "اختبار"} · {result.date}</p></div><span className="rounded-full bg-[#f9efda] px-2.5 py-1 text-xs font-bold text-[#8a651b]">{result.rating ?? "غير مقيم"} · {result.score ?? "—"}/5</span></div>; }) : <p className="rounded-xl bg-[#f6f8f5] p-4 text-sm text-[#718078]">لا توجد نتائج بعد. ابدأ من شاشة الاختبارات.</p>}</div></article>
      <article className="rounded-2xl bg-[#174a3b] p-5 text-white"><p className="text-sm font-bold text-[#f1d57f]">سلامة البيانات</p><h3 className="mt-2 text-xl font-black">المصدر المرجعي محفوظ</h3><p className="mt-3 text-sm leading-6 text-[#d9ebe0]">تعمل المنصة من IndexedDB. المعايير الرقمية والأوزان واتجاهات القياس مبنية على ملف القيم المرجعية، ولا يُستخدم معيار غير موثق في التقييم.</p><div className="mt-5 grid grid-cols-2 gap-2 text-xs"><div className="rounded-lg bg-white/10 p-3"><span className="block text-[#cce3d5]">الحالة</span><strong>Offline-first</strong></div><div className="rounded-lg bg-white/10 p-3"><span className="block text-[#cce3d5]">طابور المزامنة</span><strong>{data.metrics.pendingSync} Pending</strong></div></div></article>
    </div>
  </section>;
}
