import { CheckCircle2, CloudOff, KeyRound, Smartphone, WifiOff } from "lucide-react";
import { LOCAL_IDENTITY, ROLE_CAPABILITIES } from "@/services/futureContracts";

const readiness = [
  { title: "Offline-first", status: "جاهز", icon: WifiOff, body: "البيانات والتقييم والنسخ الاحتياطي تعمل من IndexedDB في المتصفح." },
  { title: "طابور المزامنة", status: "جاهز محليًا", icon: CloudOff, body: "تُسجَّل عمليات الإنشاء والتعديل والحذف محليًا بحالة Pending مع deviceId وlocal-user." },
  { title: "المصادقة والصلاحيات", status: "مجهز", icon: KeyRound, body: "الحقول والعقود جاهزة للتوسعة إلى Super Admin وClub Admin وCoach وViewer دون ربط فعلي الآن." },
  { title: "Android APK", status: "مجهز", icon: Smartphone, body: "تستخدم المنصة بنية ويب محلية قابلة للتغليف. يتطلب بناء APK لاحقًا Android SDK ومفتاح توقيع للتوزيع." },
];

export function ReadinessPanel() { return <section className="space-y-6"><div><p className="text-sm font-semibold text-[#ad8130]">نطاق الإطلاق</p><h2 className="mt-1 text-2xl font-black">الجاهزية التقنية</h2><p className="mt-1 text-sm text-[#718078]">ما هو متاح محليًا الآن، وما هو مجهز للتوسعة من دون تشغيل خدمات خارجية.</p></div><div className="grid gap-4 md:grid-cols-2">{readiness.map(({ title, status, icon: Icon, body }) => <article key={title} className="rounded-2xl border border-[#dbe5dc] bg-white p-5"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e8f3ea] text-[#28714d]"><Icon className="h-5 w-5"/></span><span className="flex items-center gap-1 rounded-full bg-[#eef5ef] px-2 py-1 text-xs font-bold text-[#28714d]"><CheckCircle2 className="h-3.5 w-3.5"/>{status}</span></div><h3 className="mt-5 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#718078]">{body}</p></article>)}</div><article className="rounded-2xl border border-[#dbe5dc] bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-extrabold">عقد الأدوار والمصادقة المستقبلية</h3><p className="mt-1 text-sm text-[#718078]">الهوية المحلية الحالية: <strong>{LOCAL_IDENTITY.userId}</strong> بدور <strong>{LOCAL_IDENTITY.role}</strong>. لا يتم فتح تسجيل دخول أو اتصال سحابي في هذه النسخة.</p></div><KeyRound className="h-5 w-5 text-[#ad8130]"/></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(ROLE_CAPABILITIES).map(([role, capabilities]) => <div key={role} className="rounded-xl bg-[#f6f8f5] p-3"><strong className="text-sm">{role}</strong><p className="mt-1 text-xs leading-5 text-[#718078]">{capabilities.join(" · ")}</p></div>)}</div></article></section>; }
