import { Button } from "@/components/ui/button";
import { AGE_CATEGORIES } from "@/data/referenceCatalog";
import type { AgeGroupRule, Belt, Club, TrainingGroup } from "@/domain/types";
import type { OfflineSnapshot } from "@/hooks/useOfflineData";
import { phaseA } from "@/services/phaseAService";
import { ArchiveRestore, Landmark, Pencil, Plus, Ruler, Save, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export function ReferenceDataPanel({ data, refresh }: { data: OfflineSnapshot; refresh: () => Promise<void> }) {
  const [club, setClub] = useState(""); const [belt, setBelt] = useState(""); const [groupName, setGroupName] = useState(""); const [groupCategory, setGroupCategory] = useState(AGE_CATEGORIES[0]); const [busy, setBusy] = useState(false);
  const safe = async (work: () => Promise<unknown>, success: string) => { setBusy(true); try { await work(); await refresh(); toast.success(success); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر حفظ البيانات المرجعية"); } finally { setBusy(false); } };
  return <section className="space-y-6"><div><p className="text-sm font-semibold text-[#ad8130]">Phase A · توحيد البيانات</p><h2 className="mt-1 text-2xl font-black">الأندية والأحزمة والفئات والمجموعات</h2><p className="mt-1 text-sm text-[#718078]">تُحفظ البيانات المرجعية محليًا وتمنع اختلاف التسمية. الفئة العمرية والمجموعة التدريبية كيانان منفصلان، ويقترح النظام المجموعة تلقائيًا عند إنشاء اللاعب.</p></div>
    {data.migrationReviews.length > 0 && <div className="rounded-2xl border border-[#ecd9a3] bg-[#fffaf0] p-4 text-sm text-[#70581d]"><strong>مراجعة ترحيل مطلوبة</strong><p className="mt-1">هناك {data.migrationReviews.length} حالة لم تُدمج أو تربط تلقائيًا لحماية البيانات. راجعها إداريًا قبل توحيدها.</p><ul className="mt-3 grid gap-2 sm:grid-cols-2">{data.migrationReviews.map((review) => <li key={review.id ?? `${review.entity}-${review.sourceValue}`} className="rounded-lg border border-[#ecd9a3] bg-white/70 p-2"><span className="font-bold">{review.entity === "trainingGroup" ? "مجموعة تدريبية" : review.entity === "club" ? "نادٍ" : "حزام"}</span><span className="mx-1">—</span><span>{review.sourceValue}</span><span className="mr-2 rounded-full bg-[#f5e8c5] px-2 py-0.5 text-xs font-semibold">قيد المراجعة</span></li>)}</ul></div>}
    <div className="grid gap-4 xl:grid-cols-2"><ReferenceManager icon={Landmark} title="الأندية" description="تظهر لاحقًا كقائمة موحدة عند إضافة اللاعب." value={club} onChange={setClub} onAdd={() => void safe(async () => { await phaseA.saveClub({ name: club }); setClub(""); }, "تمت إضافة النادي المرجعي")} busy={busy} items={data.clubs} save={(item) => phaseA.saveClub(item)}/><ReferenceManager icon={Ruler} title="درجات الأحزمة" description="مرتبة محليًا وتظهر في نموذج اللاعب كاختيار موحد." value={belt} onChange={setBelt} onAdd={() => void safe(async () => { await phaseA.saveBelt({ name: belt }); setBelt(""); }, "تمت إضافة الحزام المرجعي")} busy={busy} items={data.belts} save={(item) => phaseA.saveBelt(item)}/></div>
    <div className="grid gap-4 xl:grid-cols-2"><article className="rounded-2xl border border-[#dbe5dc] bg-white p-5"><div className="flex items-center gap-2"><UsersRound className="h-5 w-5 text-[#28714d]"/><h3 className="font-extrabold">قواعد الفئات العمرية</h3></div><p className="mt-1 text-sm text-[#718078]">يمكن ضبط الحدود فقط؛ تبقى مفاتيح الفئات المرجعية ثابتة حتى تظل جميع المعايير قابلة للتقييم.</p><div className="mt-4 space-y-2">{data.ageGroups.map((item) => <AgeRuleRow key={item.id} item={item} refresh={refresh}/>)}</div></article>
      <article className="rounded-2xl border border-[#dbe5dc] bg-white p-5"><div className="flex items-center gap-2"><ArchiveRestore className="h-5 w-5 text-[#ad8130]"/><h3 className="font-extrabold">المجموعات التدريبية</h3></div><p className="mt-1 text-sm text-[#718078]">تُقترح المجموعة بحسب الفئة؛ يمكن تعديل الاسم والسعة أو إضافة مجموعة تشغيلية يدويًا دون تغيير معيار اللاعب.</p><div className="mt-4 space-y-2">{data.trainingGroups.filter((item) => item.isActive).map((item) => <TrainingGroupRow key={item.id} item={item} refresh={refresh}/>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_150px_auto]"><input value={groupName} onChange={(event) => setGroupName(event.target.value)} className="h-10 rounded-xl border border-[#d9e3da] px-3 text-sm" placeholder="اسم مجموعة تدريبية"/><select value={groupCategory} onChange={(event) => setGroupCategory(event.target.value as typeof groupCategory)} className="h-10 rounded-xl border border-[#d9e3da] px-3 text-sm">{AGE_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select><Button disabled={busy} onClick={() => void safe(async () => { await phaseA.saveGroup({ name: groupName, ageGroupKey: groupCategory, isAutoSuggested: false }); setGroupName(""); }, "تمت إضافة المجموعة التدريبية")} className="bg-[#174a3b]"><Plus className="ml-1 h-4 w-4"/>إضافة</Button></div></article></div>
  </section>;
}

function ReferenceManager({ icon: Icon, title, description, value, onChange, onAdd, busy, items, save }: { icon: typeof Landmark; title: string; description: string; value: string; onChange: (value: string) => void; onAdd: () => void; busy: boolean; items: Array<Club | Belt>; save: (item: Club | Belt) => Promise<unknown> }) { return <article className="rounded-2xl border border-[#dbe5dc] bg-white p-5"><div className="flex items-center gap-2"><Icon className="h-5 w-5 text-[#28714d]"/><div><h3 className="font-extrabold">{title}</h3><p className="mt-1 text-sm text-[#718078]">{description}</p></div></div><div className="mt-4 flex gap-2"><input value={value} onChange={(event) => onChange(event.target.value)} className="h-10 min-w-0 flex-1 rounded-xl border border-[#d9e3da] px-3 text-sm" placeholder={`إضافة ${title.slice(0, -1)}`}/><Button disabled={busy || !value.trim()} onClick={onAdd} className="bg-[#174a3b]"><Plus className="ml-1 h-4 w-4"/>إضافة</Button></div><div className="mt-4 space-y-2">{items.length ? items.map((item) => <ReferenceRow key={item.id} item={item} save={save}/>) : <p className="text-sm text-[#718078]">لا توجد بيانات بعد.</p>}</div></article>; }

function ReferenceRow({ item, save }: { item: Club | Belt; save: (item: Club | Belt) => Promise<unknown> }) { const [name, setName] = useState(item.name); const [busy, setBusy] = useState(false); const execute = async (next: Club | Belt, message: string) => { setBusy(true); try { await save(next); toast.success(message); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر التحديث"); } finally { setBusy(false); } }; return <div className="flex items-center gap-2 rounded-xl bg-[#f6f8f5] p-2"><input value={name} onChange={(event) => setName(event.target.value)} className="h-8 min-w-0 flex-1 rounded-lg border border-[#d9e3da] bg-white px-2 text-sm"/><Button aria-label={`حفظ ${item.name}`} size="sm" variant="outline" disabled={busy || name.trim() === item.name} onClick={() => void execute({ ...item, name }, "تم تحديث البيانات المرجعية")}><Save className="h-3.5 w-3.5"/></Button><Button aria-label={`تعطيل ${item.name}`} size="sm" variant="outline" disabled={busy} className="text-[#a94438]" onClick={() => void execute({ ...item, isActive: !item.isActive }, item.isActive ? "تم تعطيل السجل" : "تمت إعادة تفعيل السجل")}><Pencil className="h-3.5 w-3.5"/></Button></div>; }

function AgeRuleRow({ item, refresh }: { item: AgeGroupRule; refresh: () => Promise<void> }) { const [min, setMin] = useState(String(item.minAge)); const [max, setMax] = useState(String(item.maxAge)); const [busy, setBusy] = useState(false); const save = async () => { setBusy(true); try { await phaseA.saveAgeGroup({ ...item, minAge: Number(min), maxAge: Number(max) }); await refresh(); toast.success("تم تحديث حدود الفئة مع حماية مفتاح المعيار"); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر تحديث الفئة"); } finally { setBusy(false); } }; return <div className="grid grid-cols-[1fr_60px_60px_auto] items-center gap-2 rounded-xl bg-[#f6f8f5] p-2"><strong className="text-sm">{item.name}</strong><input value={min} onChange={(event) => setMin(event.target.value)} inputMode="numeric" className="h-8 rounded-lg border border-[#d9e3da] bg-white px-2 text-center text-xs"/><input value={max} onChange={(event) => setMax(event.target.value)} inputMode="numeric" className="h-8 rounded-lg border border-[#d9e3da] bg-white px-2 text-center text-xs"/><Button size="sm" variant="outline" disabled={busy} onClick={() => void save()}><Save className="h-3.5 w-3.5"/></Button></div>; }

function TrainingGroupRow({ item, refresh }: { item: TrainingGroup; refresh: () => Promise<void> }) { const [name, setName] = useState(item.name); const [max, setMax] = useState(item.maxPlayers === null ? "" : String(item.maxPlayers)); const [busy, setBusy] = useState(false); const save = async () => { setBusy(true); try { await phaseA.saveGroup({ ...item, name, maxPlayers: max === "" ? null : Number(max) }); await refresh(); toast.success("تم تحديث المجموعة التدريبية"); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر تحديث المجموعة"); } finally { setBusy(false); } }; return <div className="grid grid-cols-[1fr_90px_auto] items-center gap-2 rounded-xl bg-[#f6f8f5] p-2"><input value={name} onChange={(event) => setName(event.target.value)} className="h-8 min-w-0 rounded-lg border border-[#d9e3da] bg-white px-2 text-sm"/><input value={max} onChange={(event) => setMax(event.target.value)} inputMode="numeric" placeholder="السعة" className="h-8 rounded-lg border border-[#d9e3da] bg-white px-2 text-xs"/><Button size="sm" variant="outline" disabled={busy} onClick={() => void save()}><Save className="h-3.5 w-3.5"/></Button></div>; }
