import type { OfflineSnapshot } from "@/hooks/useOfflineData";
import { finalEvaluation, getAge, getAgeCategory } from "@/services/evaluation";
import * as XLSX from "xlsx";

export type ReportModel = ReturnType<typeof buildReportModel>;

const clean = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character] ?? character);
const activePlayers = (data: OfflineSnapshot) => data.players.filter((player) => !player.deletedAt);

export function buildReportModel(data: OfflineSnapshot) {
  const players = activePlayers(data);
  const rankings = players.map((player) => ({ player, ...finalEvaluation(data.results.filter((result) => !result.deletedAt && result.playerId === player.id), data.tests) })).sort((left, right) => right.achievement - left.achievement || left.player.name.localeCompare(right.player.name, "ar"));
  const perTest = data.tests.map((test) => { const results = data.results.filter((result) => !result.deletedAt && result.testId === test.id && result.score !== null); return { id: test.id, name: test.nameAr, unit: test.unit, weight: test.weight, count: results.length, averageScore: results.length ? Math.round((results.reduce((sum, result) => sum + (result.score ?? 0), 0) / results.length) * 100) / 100 : null }; });
  const attendance = data.attendance.filter((record) => players.some((player) => player.id === record.playerId));
  return { generatedAt: new Date().toISOString(), summary: { playerCount: players.length, resultCount: data.results.filter((result) => !result.deletedAt).length, attendanceCount: attendance.length, averageTeamAchievement: data.metrics.averageTeamAchievement, excellentPercentage: data.metrics.excellentPercentage }, rankings, perTest, players, results: data.results.filter((result) => !result.deletedAt), attendance, sessions: data.sessions.filter((session) => !session.deletedAt) };
}

function sheet(rows: Array<Record<string, string | number | null>>) { const worksheet = XLSX.utils.json_to_sheet(rows); worksheet["!views"] = [{ rightToLeft: true }]; worksheet["!cols"] = Object.keys(rows[0] ?? {}).map((key) => ({ wch: Math.max(12, Math.min(34, key.length + 12)) })); return worksheet; }

export function createExcelWorkbook(data: OfflineSnapshot) {
  const report = buildReportModel(data); const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, sheet([{ "تاريخ التقرير": report.generatedAt.slice(0, 10), "عدد اللاعبين": report.summary.playerCount, "النتائج المقيمة": report.summary.resultCount, "متوسط إنجاز الفريق %": report.summary.averageTeamAchievement, "نسبة الممتاز %": report.summary.excellentPercentage }]), "ملخص الفريق");
  XLSX.utils.book_append_sheet(workbook, sheet(report.rankings.map(({ player, achievement, finalGrade }) => ({ "اللاعب": player.name, "الجنس": player.gender, "سنة الميلاد": player.birthYear, "الفئة": getAgeCategory(getAge(player.birthYear), player.gender), "الإنجاز %": achievement, "التقدير": finalGrade, "النادي": player.club ?? "", "الحزام": player.belt ?? "" }))), "اللاعبون");
  XLSX.utils.book_append_sheet(workbook, sheet(report.results.map((result) => ({ "اللاعب": report.players.find((player) => player.id === result.playerId)?.name ?? "سجل محلي", "الاختبار": data.tests.find((test) => test.id === result.testId)?.nameAr ?? `اختبار #${result.testId}`, "القيمة": result.value, "الوحدة": data.tests.find((test) => test.id === result.testId)?.unit ?? "", "الدرجة": result.score, "التقدير": result.rating, "التاريخ": result.date, "ملاحظات": result.notes }))), "النتائج");
  XLSX.utils.book_append_sheet(workbook, sheet(report.attendance.map((record) => ({ "اللاعب": report.players.find((player) => player.id === record.playerId)?.name ?? "سجل محلي", "التاريخ": record.date, "الحالة": record.status, "الموسم": record.season, "الشهر": record.month, "النادي": record.club, "ملاحظات": record.notes }))), "الحضور");
  XLSX.utils.book_append_sheet(workbook, sheet(report.sessions.map((session) => ({ "الجلسة": session.name, "التاريخ": session.date, "الاختبار": data.tests.find((test) => test.id === session.testId)?.nameAr ?? `اختبار #${session.testId}`, "المشاركون": session.playerIds.map((id) => report.players.find((player) => player.id === id)?.name ?? `#${id}`).join("، "), "الحالة": session.status, "الدفعة": session.currentBatch + 1, "حجم الدفعة": session.batchSize }))), "الجلسات");
  return workbook;
}

export function downloadExcelReport(data: OfflineSnapshot) { XLSX.writeFile(createExcelWorkbook(data), `judo-performance-report-${new Date().toISOString().slice(0, 10)}.xlsx`, { compression: true }); }

export function buildPrintableReportHtml(data: OfflineSnapshot, playerId?: number) {
  const report = buildReportModel(data); const selected = playerId ? report.rankings.find((row) => row.player.id === playerId) : undefined; const rows = selected ? [{ name: selected.player.name, gender: selected.player.gender, birthYear: selected.player.birthYear, ageCategory: getAgeCategory(getAge(selected.player.birthYear), selected.player.gender), achievement: selected.achievement, finalGrade: selected.finalGrade, results: report.results.filter((result) => result.playerId === selected.player.id), attendance: report.attendance.filter((record) => record.playerId === selected.player.id) }] : report.rankings.map(({ player, achievement, finalGrade }) => ({ name: player.name, gender: player.gender, birthYear: player.birthYear, ageCategory: getAgeCategory(getAge(player.birthYear), player.gender), achievement, finalGrade, results: report.results.filter((result) => result.playerId === player.id), attendance: report.attendance.filter((record) => record.playerId === player.id) }));
  const cards = rows.map((row) => `<article><h2>${clean(row.name)}</h2><p>الجنس: ${clean(row.gender)} · سنة الميلاد: ${row.birthYear} · الفئة: ${clean(row.ageCategory)}</p><p><strong>الإنجاز: ${row.achievement}% · التقدير النهائي: ${clean(row.finalGrade)}</strong></p><h3>النتائج (${row.results.length})</h3><table><thead><tr><th>الاختبار</th><th>القيمة</th><th>الدرجة</th><th>التقدير</th><th>التاريخ</th></tr></thead><tbody>${row.results.map((result) => `<tr><td>${clean(data.tests.find((test) => test.id === result.testId)?.nameAr ?? result.testId)}</td><td>${result.value}</td><td>${result.score ?? "—"}</td><td>${clean(result.rating ?? "—")}</td><td>${clean(result.date)}</td></tr>`).join("") || "<tr><td colspan=5>لا توجد نتائج مسجلة</td></tr>"}</tbody></table><p>الحضور: ${row.attendance.filter((record) => record.status === "present").length} حضور من ${row.attendance.length} سجل.</p></article>`).join("");
  const title = selected ? "بطاقة أداء اللاعب" : "تقرير أداء الفريق";
  return { title, html: `<section lang="ar" dir="rtl"><style>*{box-sizing:border-box}.judo-report{font-family:Arial,"Noto Sans Arabic",sans-serif;color:#173d32;width:760px;background:#fff;padding:28px;line-height:1.6}.judo-report h1{margin:0;color:#174a3b;font-size:26px}.judo-report h2{margin-bottom:4px;color:#174a3b;font-size:19px}.judo-report h3{font-size:15px}.judo-report article{border:1px solid #dbe5dc;border-radius:12px;padding:16px;margin:16px 0;break-inside:avoid}.judo-report table{width:100%;border-collapse:collapse;font-size:12px}.judo-report th,.judo-report td{border:1px solid #dbe5dc;padding:7px;text-align:right}.judo-report th{background:#edf5ee}</style><main class="judo-report"><h1>${title}</h1><p>تاريخ الإنشاء: ${new Date(report.generatedAt).toLocaleDateString("ar-EG")}</p>${!selected ? `<p>عدد اللاعبين: ${report.summary.playerCount} · متوسط الإنجاز: ${report.summary.averageTeamAchievement}% · نسبة الممتاز: ${report.summary.excellentPercentage}%</p>` : ""}${cards}</main></section>` };
}

export async function createPdfReportBlob(data: OfflineSnapshot, playerId?: number) {
  if (typeof document === "undefined") throw new Error("يتطلب إنشاء PDF بيئة متصفح أو Android.");
  const report = buildReportModel(data); const selected = playerId ? report.rankings.find((row) => row.player.id === playerId) : undefined; const ranking = selected ? [selected] : report.rankings;
  const lines = [selected ? "بطاقة أداء اللاعب" : "تقرير أداء الفريق", `تاريخ الإنشاء: ${new Date(report.generatedAt).toLocaleDateString("ar-EG")}`, ...(selected ? [] : [`عدد اللاعبين: ${report.summary.playerCount}`, `متوسط الإنجاز: ${report.summary.averageTeamAchievement}%`, `نسبة الممتاز: ${report.summary.excellentPercentage}%`]), "", ...ranking.flatMap(({ player, achievement, finalGrade }) => [player.name, `الجنس: ${player.gender} · سنة الميلاد: ${player.birthYear} · الفئة: ${getAgeCategory(getAge(player.birthYear), player.gender)}`, `الإنجاز: ${achievement}% · التقدير النهائي: ${finalGrade}`, "النتائج:", ...(report.results.filter((result) => result.playerId === player.id).map((result) => `${data.tests.find((test) => test.id === result.testId)?.nameAr ?? `اختبار #${result.testId}`} — ${result.value} ${data.tests.find((test) => test.id === result.testId)?.unit ?? ""} — ${result.rating ?? "غير مقيم"} — ${result.date}`) || ["لا توجد نتائج مسجلة"]), `الحضور: ${report.attendance.filter((record) => record.playerId === player.id && record.status === "present").length} حضور من ${report.attendance.filter((record) => record.playerId === player.id).length} سجل`, ""])];
  const { jsPDF } = await import("jspdf"); const pdf = new jsPDF({ orientation: "p", unit: "mm", format: "a4", compress: true }); const canvas = document.createElement("canvas"); canvas.width = 1600; canvas.height = 2200; const context = canvas.getContext("2d"); if (!context) throw new Error("تعذر تهيئة رسم PDF المحلي."); let firstPage = true; let y = 100;
  const beginPage = () => { context.fillStyle = "#ffffff"; context.fillRect(0, 0, canvas.width, canvas.height); context.direction = "rtl"; context.textAlign = "right"; context.fillStyle = "#173d32"; context.font = "32px Arial, sans-serif"; y = 100; };
  const commitPage = () => { if (!firstPage) pdf.addPage(); pdf.addImage(canvas.toDataURL("image/png"), "PNG", 0, 0, 210, 297, undefined, "FAST"); firstPage = false; };
  const wrap = (text: string) => { const words = text.split(" "); const wrapped: string[] = []; let line = ""; for (const word of words) { const candidate = line ? `${line} ${word}` : word; if (context.measureText(candidate).width > 1400 && line) { wrapped.push(line); line = word; } else line = candidate; } if (line) wrapped.push(line); return wrapped; };
  beginPage(); for (const sourceLine of lines) { const isName = sourceLine && !sourceLine.includes(":") && !sourceLine.includes("—") && !["النتائج:"].includes(sourceLine); context.font = isName ? "bold 40px Arial, sans-serif" : "30px Arial, sans-serif"; for (const line of wrap(sourceLine)) { if (y > 2070) { commitPage(); beginPage(); } context.fillText(line, 1500, y); y += isName ? 64 : 48; } } commitPage(); return pdf.output("blob");
}

export async function downloadPdfReport(data: OfflineSnapshot, playerId?: number) { const blob = await createPdfReportBlob(data, playerId); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `judo-performance-report-${new Date().toISOString().slice(0, 10)}.pdf`; link.click(); window.setTimeout(() => URL.revokeObjectURL(link.href), 0); }
